error_page 400 401 403 500 502 503 504 @error_handler;
error_page 404 = @notfound_handler;

location @error_handler {
    internal;
    root ${NGINX_ERROR_ROOT};
    try_files /${status}.${error_file_ext} /${status}.html /500.html =500;
}

location @notfound_handler {
    fastcgi_pass unix:/run/php-fpm.sock;
    fastcgi_param SCRIPT_FILENAME $document_root/index.php;
    fastcgi_param REQUEST_URI /404;
    include fastcgi_params;
}
