/* repro.svelte.js generated by Svelte v5.56.8 */
import * as $ from 'svelte/internal/client';
import { flushSync } from 'svelte';

class ListCtx {
	#filter = $.state($.proxy({}));

	get filter() {
		return $.get(this.#filter);
	}

	set filter(value) {
		$.set(this.#filter, value, true);
	}

	#perPage = $.state(20);

	get perPage() {
		return $.get(this.#perPage);
	}

	set perPage(value) {
		$.set(this.#perPage, value, true);
	}

	#loading = $.state(false);

	get loading() {
		return $.get(this.#loading);
	}

	set loading(value) {
		$.set(this.#loading, value, true);
	}

	#assistants = $.state($.proxy([]));

	get assistants() {
		return $.get(this.#assistants);
	}

	set assistants(value) {
		$.set(this.#assistants, value, true);
	}

	setFilter(f) {
		this.filter = f;

		return this.load(1);
	}

	buildFilter() {
		const o = {};

		if (this.filter.name) o.name = this.filter.name;

		return o;
	}

	async load(page) {
		this.loading = true;

		const args = {
			// <- built synchronously, inside the effect
			filter: this.buildFilter(), // <- READS this.filter
			page: { number: page, size: this.perPage }
		};

		await Promise.resolve(); // stand-in for the network call
		this.assistants = [];
		this.perPage = args.page.size;
		this.loading = false;
	}
}

export function run(label, useUntrack, filterIsState) {
	const ctx = new ListCtx();

	if (!filterIsState) {
		/* emulate plain field */
	}

	let runs = 0;

	const cleanup = $.effect_root(() => {
		let searchQuery = '';
		let activeFilters = $.proxy(new Set());

		$.user_effect(() => {
			if (++runs > 25) return; // bail out so we don't hang

			const name = searchQuery;
			const cats = [...activeFilters];
			const payload = { name, assistant_category: cats, release_stage: ['a', 'b'] };

			if (useUntrack) {
				$.effect_tracking(); // no-op, keeps shape similar
				untrackCall(() => ctx.setFilter(payload));
			} else {
				ctx.setFilter(payload);
			}
		});
	});

	flushSync();

	return { label, runs };
}

import { untrack as untrackCall } from 'svelte';