import type {Plugin} from 'vite';
import {existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync} from 'node:fs';
import {resolve} from 'node:path';

// Bump this when the generated file template changes to force regeneration.
const PLUGIN_VERSION = '3';

type IconData = readonly (readonly [string, Record<string, string | number>])[];

function iconsPkgVersion(): string {
    const pkgJson = JSON.parse(
        readFileSync(
            resolve(process.cwd(), 'node_modules/@hugeicons/core-free-icons/package.json'),
            'utf-8'
        )
    ) as { version: string };
    return pkgJson.version;
}

function needsRegeneration(outputDir: string): boolean {
    const markerPath = resolve(outputDir, '.gen-version');
    if (!existsSync(markerPath)) return true;
    const expected = `${iconsPkgVersion()}:${PLUGIN_VERSION}`;
    return readFileSync(markerPath, 'utf-8').trim() !== expected;
}

function writeVersionMarker(outputDir: string): void {
    writeFileSync(
        resolve(outputDir, '.gen-version'),
        `${iconsPkgVersion()}:${PLUGIN_VERSION}`,
        'utf-8'
    );
}

async function loadAllIcons(): Promise<Map<string, IconData>> {
    const pkg = await import('@hugeicons/core-free-icons') as Record<string, unknown>;
    const icons = new Map<string, IconData>();
    for (const [name, data] of Object.entries(pkg)) {
        if (name.endsWith('Icon') && Array.isArray(data)) {
            icons.set(name, data as IconData);
        }
    }
    return icons;
}

// Some @hugeicons/core-free-icons exports differ only in casing (e.g. BarCodeIcon vs
// BarcodeIcon). Written as separate .svelte files, those collide into a single file on
// case-insensitive file systems (macOS, Windows), so keep only one per case-insensitive name.
//
// The package also re-exports many icons under a second, unrelated name that points at the
// exact same array object (e.g. `exports.BarCodeIcon = BarCode01Icon`) — a deliberate
// "shorthand alias" convention used package-wide, not specific to the casing collisions.
// When a casing collision involves one of these aliases, keep the name that is the *only*
// reference to its artwork rather than the alias, so we don't discard the one file that
// actually renders that icon's unique design in favor of a redundant duplicate.
function dedupeCaseInsensitive(icons: Map<string, IconData>): Map<string, IconData> {
    const namesByData = new Map<IconData, string[]>();
    for (const [name, data] of icons) {
        const names = namesByData.get(data) ?? [];
        names.push(name);
        namesByData.set(data, names);
    }
    const isRedundantAliasElsewhere = (name: string, data: IconData): boolean =>
        namesByData.get(data)!.some(other => other !== name);

    const deduped = new Map<string, IconData>();
    const seenLowerCase = new Map<string, string>();
    const skipped: string[] = [];

    for (const name of [...icons.keys()].sort()) {
        const lowerCaseName = name.toLowerCase();
        const data = icons.get(name)!;
        const existingName = seenLowerCase.get(lowerCaseName);

        if (existingName === undefined) {
            seenLowerCase.set(lowerCaseName, name);
            deduped.set(name, data);
            continue;
        }

        const existingData = deduped.get(existingName)!;
        const existingIsAlias = isRedundantAliasElsewhere(existingName, existingData);
        const currentIsAlias = isRedundantAliasElsewhere(name, data);

        if (existingIsAlias && !currentIsAlias) {
            deduped.delete(existingName);
            deduped.set(name, data);
            seenLowerCase.set(lowerCaseName, name);
            skipped.push(`${existingName} (kept ${name})`);
        } else {
            skipped.push(`${name} (kept ${existingName})`);
        }
    }

    if (skipped.length > 0) {
        console.warn(
            `[vite-plugin-hugeicons] Skipped ${skipped.length} icon(s) whose name differs only in ` +
            `casing from another icon (would collide on case-insensitive file systems): ${skipped.join(', ')}`
        );
    }

    return deduped;
}

function stripReactKey(data: IconData): unknown[][] {
    return data.map(([tag, attrs]) => {
        const {key: _key, ...rest} = attrs as Record<string, unknown>;
        return [tag, rest];
    });
}

function generateSvelteFile(data: IconData): string {
    return `<!-- Auto-generated by vitePluginHugeicons — do not edit. -->
<script lang="ts">
    import {HugeiconsIcon, type HugeiconsProps, type IconSvgElement} from '@hugeicons/svelte';
    const iconData:IconSvgElement = ${JSON.stringify(stripReactKey(data))};
    let {...props}: HugeiconsProps = $props();
</script>
<HugeiconsIcon icon={iconData} strokeWidth={2} {...props} />
`;
}

export function vitePluginHugeicons(outputDir: string): Plugin {
    async function generate() {
        if (!needsRegeneration(outputDir)) return;

        mkdirSync(outputDir, {recursive: true});
        for (const entry of readdirSync(outputDir)) {
            if (entry.endsWith('.svelte')) {
                rmSync(resolve(outputDir, entry));
            }
        }

        const icons = dedupeCaseInsensitive(await loadAllIcons());

        for (const [name, data] of icons) {
            writeFileSync(resolve(outputDir, `${name}.svelte`), generateSvelteFile(data), 'utf-8');
        }

        writeVersionMarker(outputDir);
    }

    return {
        name: 'vite-plugin-hugeicons',
        async buildStart() {
            await generate();
        },
        configureServer() {
            void generate();
        }
    };
}
