import type { Plugin } from 'vite';
import { readFileSync, writeFileSync } from 'node:fs';

const EXACT_SIZE_NAMES = new Set(['xxs', 'xs', 'sm', 'md', 'lg', 'xl']);
const CSS_RE = /@custom-media\s+--bp-([\w-]+)\s+(.+?);/g;

function nameToKey(bpName: string): string {
    const camel = bpName.replace(/-([a-z0-9])/gi, (_, c: string) => c.toUpperCase());
    return 'bp' + camel.charAt(0).toUpperCase() + camel.slice(1);
}

interface BreakpointEntry {
    key: string;
    query: string;
    isExact: boolean;
}

function parseCss(css: string): BreakpointEntry[] {
    const entries: BreakpointEntry[] = [];
    CSS_RE.lastIndex = 0;
    let match: RegExpExecArray | null;
    while ((match = CSS_RE.exec(css)) !== null) {
        entries.push({
            key: nameToKey(match[1]),
            query: match[2].trim(),
            isExact: EXACT_SIZE_NAMES.has(match[1]),
        });
    }
    return entries;
}

function generateTs(entries: BreakpointEntry[]): string {
    const queriesLines = entries
        .map(e => `    ${e.key}: '${e.query}',`)
        .join('\n');

    const exactLines = entries
        .filter(e => e.isExact)
        .map(e => `    ${e.key}?: Snippet;`)
        .join('\n');

    const rangeLines = entries
        .filter(e => !e.isExact)
        .map(e => `    ${e.key}?: Snippet;`)
        .join('\n');

    return `// Auto-generated by vitePluginBreakpoints — do not edit manually.
import type { Snippet } from 'svelte';

export const breakpointsQueries = {
${queriesLines}
} as const;

export type Breakpoint = keyof typeof breakpointsQueries;

export interface BreakpointExactProps {
${exactLines}
}

export interface BreakpointRangeProps {
${rangeLines}
}

export interface BreakpointSnippetProps extends BreakpointExactProps, BreakpointRangeProps {
    /** Rendered only when no breakpoint snippet matches the current viewport. */
    children?: Snippet;
}
`;
}

export function vitePluginBreakpoints(cssPath: string, tsPath: string): Plugin {
    function generate() {
        const css = readFileSync(cssPath, 'utf-8');
        writeFileSync(tsPath, generateTs(parseCss(css)), 'utf-8');
    }

    return {
        name: 'vite-plugin-breakpoints',
        buildStart() {
            generate();
        },
        configureServer(server) {
            generate();
            server.watcher.add(cssPath);
            server.watcher.on('change', (file: string) => {
                if (file === cssPath) generate();
            });
        },
    };
}
