import type {Plugin} from 'vite';
import {existsSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {resolve} from 'node:path';

// Bump this when the generated file template changes to force regeneration.
const PLUGIN_VERSION = '1';

type IconData = readonly (readonly [string, Record<string, string | number>])[];

function iconsPkgVersion(): string {
    const pkgJson = JSON.parse(
        readFileSync(
            resolve(process.cwd(), 'node_modules/@hugeicons/core-free-icons/package.json'),
            'utf-8'
        )
    ) as { version: string };
    return pkgJson.version;
}

function needsRegeneration(outputDir: string): boolean {
    const markerPath = resolve(outputDir, '.gen-version');
    if (!existsSync(markerPath)) return true;
    const expected = `${iconsPkgVersion()}:${PLUGIN_VERSION}`;
    return readFileSync(markerPath, 'utf-8').trim() !== expected;
}

function writeVersionMarker(outputDir: string): void {
    writeFileSync(
        resolve(outputDir, '.gen-version'),
        `${iconsPkgVersion()}:${PLUGIN_VERSION}`,
        'utf-8'
    );
}

async function loadAllIcons(): Promise<Map<string, IconData>> {
    const pkg = await import('@hugeicons/core-free-icons') as Record<string, unknown>;
    const icons = new Map<string, IconData>();
    for (const [name, data] of Object.entries(pkg)) {
        if (name.endsWith('Icon') && Array.isArray(data)) {
            icons.set(name, data as IconData);
        }
    }
    return icons;
}

function stripReactKey(data: IconData): unknown[][] {
    return data.map(([tag, attrs]) => {
        const {key: _key, ...rest} = attrs as Record<string, unknown>;
        return [tag, rest];
    });
}

function generateSvelteFile(data: IconData): string {
    return `<!-- Auto-generated by vitePluginHugeicons — do not edit. -->
<script lang="ts">
    import {HugeiconsIcon, type HugeiconsProps, type IconSvgElement} from '@hugeicons/svelte';
    const iconData:IconSvgElement = ${JSON.stringify(stripReactKey(data))};
    let {...props}: HugeiconsProps = $props();
</script>
<HugeiconsIcon icon={iconData} strokeWidth={2} {...props} />
`;
}

export function vitePluginHugeicons(outputDir: string): Plugin {
    async function generate() {
        if (!needsRegeneration(outputDir)) return;

        mkdirSync(outputDir, {recursive: true});
        const icons = await loadAllIcons();

        for (const [name, data] of icons) {
            writeFileSync(resolve(outputDir, `${name}.svelte`), generateSvelteFile(data), 'utf-8');
        }

        writeVersionMarker(outputDir);
    }

    return {
        name: 'vite-plugin-hugeicons',
        async buildStart() {
            await generate();
        },
        configureServer() {
            void generate();
        }
    };
}
