# =====================================================
# HAWKI - Development Docker Compose Configuration
# =====================================================
# Development environment with:
# - Live code mounting (read-write)
# - Debug mode enabled
# - Adminer for database management
# - Hot reload capabilities
# =====================================================

services:
    # ====================================================
    # Application Container (PHP-FPM) - DEV
    # ====================================================
    app:
        container_name: ${PROJECT_NAME}-app
        image: ${PROJECT_HAWKI_IMAGE}
        build:
            context: ..
            dockerfile: Dockerfile
            target: app_dev
            args:
                DOCKER_UID: ${DOCKER_UID:-501}
                DOCKER_GID: ${DOCKER_GID:-1000}
        restart: no
        volumes:
            # Live code mount for development
            - ..:/var/www/html:rw
            # Environment file
            - ./env/.env:/var/www/html/.env
            # Config overrides
            - ./config/model_providers.php:/var/www/html/config/model_providers.php:ro
            - ./config/model_lists:/var/www/html/config/model_lists:ro
        healthcheck:
            test: cgi-fcgi -bind -connect 127.0.0.1:9000 || exit 1
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 30s
        env_file:
            - ./env/.env
        environment:
            REVERB_HOST: ${APP_URL}
        depends_on:
            mysql:
                condition: service_healthy
                
    # ====================================================
    # Queue Worker - DEV
    # ====================================================
    queue:
        container_name: ${PROJECT_NAME}-queue
        image: ${PROJECT_HAWKI_IMAGE}
        restart: always
        volumes:
            - ..:/var/www/html:rw
            - ./env/.env:/var/www/html/.env
            - ./config/model_providers.php:/var/www/html/config/model_providers.php:ro
        env_file:
            - ./env/.env
        environment:
            REVERB_HOST: reverb
            REVERB_PORT: 8080
            REVERB_SCHEME: http
        command: [ 'php', 'artisan', 'queue:work', '--queue=default,mails,message_broadcast', '--tries=3', '--timeout=90' ]
        depends_on:
            mysql:
                condition: service_healthy
                
    # ====================================================
    # Laravel Reverb (WebSocket Server) - DEV
    # ====================================================
    reverb:
        container_name: ${PROJECT_NAME}-reverb
        image: ${PROJECT_HAWKI_IMAGE}
        restart: always
        volumes:
            - ..:/var/www/html:rw
            - ./env/.env:/var/www/html/.env
            - ./config/model_providers.php:/var/www/html/config/model_providers.php:ro
        env_file:
            - ./env/.env
        command: [ 'php', 'artisan', 'reverb:start' ]
        depends_on:
            mysql:
                condition: service_healthy
                
    # ====================================================
    # Task Scheduler - DEV
    # ====================================================
    scheduler:
        container_name: ${PROJECT_NAME}-scheduler
        image: ${PROJECT_HAWKI_IMAGE}
        restart: always
        volumes:
            - ..:/var/www/html:rw
            - ./env/.env:/var/www/html/.env
            - ./config/model_providers.php:/var/www/html/config/model_providers.php:ro
        env_file:
            - ./env/.env
        command: [ 'php', 'artisan', 'schedule:work' ]
        depends_on:
            mysql:
                condition: service_healthy
    
    # ====================================================
    # Adminer (Database Management - Dev Only)
    # ====================================================
    adminer:
        container_name: ${PROJECT_NAME}-adminer
        image: adminer:latest
        restart: no
        environment:
            ADMINER_DEFAULT_SERVER: mysql
        depends_on:
            mysql:
                condition: service_healthy
            
    # ====================================================
    # Nginx Web Server - DEV
    # ====================================================
    nginx:
        container_name: ${PROJECT_NAME}-nginx
        image: nginx:1.27-alpine
        volumes:
            - ./certs:/etc/nginx/certs
            - ./nginx/nginx.default.conf:/etc/nginx/nginx.conf:ro
            # Live public directory
            - ../public:/var/www/html/public:ro
            # Storage for uploads (from main project)
            - ../storage/app/public:/var/www/html/storage:ro
        ports:
            - ${DOCKER_PROJECT_IP:-0.0.0.0}:80:8080
            - ${DOCKER_PROJECT_IP:-0.0.0.0}:443:8443
        depends_on:
            - app
        healthcheck:
            test: curl --fail http://localhost:8080 || exit 1
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 10s
            
    # ====================================================
    # File Converter Service
    # ====================================================
    file-converter:
        image: digitalenvironments/hawki-toolkit-file-converter:1.0.0
        container_name: ${PROJECT_NAME}-file-converter
        platform: linux/amd64
        restart: always
        env_file:
            - ./env/.env
        environment:
            - F_API_KEY=${HAWKI_FILE_CONVERTER_API_KEY:-}
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8001/" ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
            
    # ====================================================
    # Redis Cache
    # ====================================================
    redis:
        container_name: ${PROJECT_NAME}-redis
        image: redis:latest
        restart: always
        env_file:
            - ./env/.env
        volumes:
            - redis_data:/root/redis
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD:-password}
            REDIS_PORT: ${REDIS_PORT:-6379}
            REDIS_DATABASES: 16
            
    # ====================================================
    # MySQL Database
    # ====================================================
    mysql:
        container_name: ${PROJECT_NAME}-mysql
        image: mysql:8.0
        command:
            - --default-authentication-plugin=mysql_native_password
            - --max_connections=2000
        env_file:
            - ./env/.env
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
            MYSQL_DATABASE: ${DB_DATABASE:-hawki}
            MYSQL_USER: ${DB_USERNAME:-hawki}
            MYSQL_PASSWORD: ${DB_PASSWORD:-password}
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        restart: no
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - ${DOCKER_PROJECT_IP:-127.0.0.1}:${DB_PORT:-3306}:3306
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME:-hawki}", "-p${DB_PASSWORD:-secret}"]
            start_period: 10s
            timeout: 20s
            interval: 5s
            retries: 10

# ====================================================
# Volumes
# ====================================================
volumes:
    mysql_data:
        driver: local
    redis_data:
        driver: local
