<?php

namespace App\Services\Auth\Http;

use App\Services\Auth\Value\Local\GuestUserRequestData;
use Illuminate\Container\Attributes\Config;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Orchid\Platform\Models\Role;

class GuestUserRequest extends FormRequest
{
    public function rules(): array
    {
        $availableRoles = Role::pluck('slug')->toArray();
        $rolesList = implode(',', $availableRoles);

        return [
            'username' => [
                'required',
                'string',
                'min:3',
                'max:255',
                'regex:/^[a-zA-Z0-9_-]+$/',
                'unique:users,username',
            ],
            'password' => [
                'required',
                'string',
                'min:8',
                'regex:/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).*$/',
            ],
            'password_confirmation' => 'required|string|same:password',
            'email' => 'required|email|max:255|unique:users,email',
            'employeetype' => "required|string|in:{$rolesList}",
        ];
    }

    /**
     * @inheritDoc
     */
    protected function failedValidation(Validator $validator)
    {
        logFile($validator->failed());
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }


    public function messages(): array
    {
        return [
            'username.required' => 'Username is required',
            'username.min' => 'Username must be at least 3 characters long',
            'username.regex' => 'Username can only contain letters, numbers, underscores, and hyphens',
            'username.unique' => 'This username is already taken',
            'password.required' => 'Password is required',
            'password.min' => 'Password must be at least 8 characters long',
            'password.regex' => 'Password must contain at least one uppercase letter, one lowercase letter, and one number',
            'password_confirmation.required' => 'Password confirmation is required',
            'password_confirmation.same' => 'Passwords do not match',
            'email.required' => 'Email is required',
            'email.email' => 'Please enter a valid email address',
            'email.unique' => 'This email address is already registered',
            'employeetype.required' => 'User group is required',
            'employeetype.in' => 'Please select a valid user group',
        ];
    }

    public function authorize(
        #[Config('auth.local_authentication')]
        bool $localAuthenticationEnabled,
        #[Config('auth.local_selfservice')]
        bool $localSelfServiceEnabled
    ): bool
    {
        logFile($localAuthenticationEnabled, $localAuthenticationEnabled);
        return $localAuthenticationEnabled && $localSelfServiceEnabled;
    }

    public function getData(): GuestUserRequestData
    {
        return new GuestUserRequestData(
            username: $this->validated('username'),
            password: $this->validated('password'),
            passwordConfirmation: $this->validated('password_confirmation'),
            email: $this->validated('email'),
            employeeType: $this->validated('employeetype'),
        );
    }
}
