<?php

namespace App\JsonApi\V1\SystemModels;

use App\Models\Ai\SystemModel;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use LaravelJsonApi\Eloquent\Fields\ID;
use LaravelJsonApi\Eloquent\Fields\Relations\HasOne;
use LaravelJsonApi\Eloquent\Fields\Str;
use LaravelJsonApi\Eloquent\Filters\Where;
use LaravelJsonApi\Eloquent\QueryBuilder\JsonApiBuilder;
use LaravelJsonApi\Eloquent\Schema;

class SystemModelSchema extends Schema
{
    /**
     * The model the schema corresponds to.
     *
     * @var string
     */
    public static string $model = SystemModel::class;

    /**
     * Get the resource fields.
     *
     * @return array
     */
    public function fields(): array
    {
        return [
            ID::make(),
            Str::make('model_type'),
            Str::make('usage_type'),
            Str::make('model_id'),
            HasOne::make('model')->type('ai-models')->readOnly(),
        ];
    }

    /**
     * Get the resource filters.
     *
     * @return array
     */
    public function filters(): array
    {
        return [
            Where::make('usage_type'),
            Where::make('model_type'),
            Where::make('model_id'),
        ];
    }

    public function indexQuery(?Request $request, Builder $query): Builder
    {
        if (!$request->query->has('filter.usage_type')) {
            $request->query->set('filter.usage_type', $request->getUsageContext()->get());
        }
        return $query;
    }

    public function newQuery($query = null): JsonApiBuilder
    {
        return parent::newQuery($query); // TODO: Change the autogenerated stub
    }
}
