# Laravel Reverb
# The Websocket Client/Laravel Echo would connect and listen to this
location ~ /app/(?<reverbkey>.*) { # variable reverbkey
  set $upstream_reverb http://${REVERB_HOST}:8080/app/$reverbkey;
  proxy_pass $upstream_reverb;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $connection_upgrade; # Use the mapped value
  proxy_set_header Host $host; # Use $host instead of $http_host sometimes needed
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme; # Ensure this is present
  proxy_set_header X-Forwarded-Host $host; # Good practice
  proxy_set_header X-Forwarded-Port $server_port; # Good practice
  proxy_connect_timeout 60s;
  proxy_send_timeout    600s;
  proxy_read_timeout    600s;
  proxy_buffering off;
}

# The Laravel Backend would broadcast to this
location ~ ^/apps/(?<reverbid>[^/]+)/events$ { # variable reverbid
  set $upstream_reverb_events http://${REVERB_HOST}:8080/apps/$reverbid/events;
  proxy_pass $upstream_reverb_events;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
}
