<?php
declare(strict_types=1);


namespace App\Services\System\JsonApi\Extensions;


use LaravelJsonApi\Encoder\Neomerx\Factory\Factory;
use Neomerx\JsonApi\Contracts\Parser\RelationshipDataInterface;
use Neomerx\JsonApi\Contracts\Parser\RelationshipInterface;
use Neomerx\JsonApi\Contracts\Schema\PositionInterface;

class ExtendedNeomerxFactory extends Factory
{
    /**
     * @inheritDoc
     */
    public function createRelationship(
        PositionInterface          $position,
        bool                       $hasData,
        ?RelationshipDataInterface $data,
        bool                       $hasLinks,
        ?iterable                  $links,
        bool                       $hasMeta,
                                   $meta
    ): RelationshipInterface
    {
        dbge(func_get_args());
        return parent::createRelationship($position, $hasData, $data, $hasLinks, $links, $hasMeta, $meta); // TODO: Change the autogenerated stub
    }

}
