<?php

declare(strict_types=1);

namespace App\Services\System\Database\SettingsAndConfig\Make;

use App\Services\System\Time\CarbonClockInterface;
use Illuminate\Container\Attributes\Singleton;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Str;

/**
 * Writes the migration files generated by the `make:config-schema-migration` and
 * `make:user-settings-migration` commands into `database/migrations`.
 *
 * The commands build the migration content (flavour-specific schema calls); this
 * creator only stamps the timestamped file name and persists the file.
 */
#[Singleton()]
class SchemaMigrationCreator
{
    public function __construct(
        private readonly CarbonClockInterface $clock,
        private readonly Filesystem $files,
    ) {
    }

    /**
     * Writes a migration file with the given name (timestamped) and content, and
     * returns its absolute path.
     */
    public function create(string $name, string $content): string
    {
        $fileName = $this->clock->now()->format('Y_m_d_His') . '_' . Str::snake($name) . '.php';
        $path = database_path('migrations/' . $fileName);

        $this->files->put($path, $content);

        return $path;
    }
}
