<?php
return [
    [
        'active' => env('MODELS_ANTHROPIC_CLAUDE_3_5_SONNET_ACTIVE', true),
        'id' => 'claude-3-5-sonnet-20241022',
        'label' => 'Claude 3.5 Sonnet',
        'input' => ['text', 'image'],
        'output' => ['text'],
        'tools' => [
            'stream' => true,
            'file_upload' => env('MODELS_ANTHROPIC_CLAUDE_3_5_SONNET_TOOLS_FILE_UPLOAD', true),
            'vision' => env('MODELS_ANTHROPIC_CLAUDE_3_5_SONNET_TOOLS_VISION', true),
            'web_search' => env('MODELS_ANTHROPIC_CLAUDE_3_5_SONNET_TOOLS_WEB_SEARCH', true),
        ],
        'external' => env('MODELS_ANTHROPIC_CLAUDE_3_5_SONNET_EXTERNAL', true),
    ],
    [
        'active' => env('MODELS_ANTHROPIC_CLAUDE_3_5_HAIKU_ACTIVE', true),
        'id' => 'claude-3-5-haiku-20241022',
        'label' => 'Claude 3.5 Haiku',
        'input' => ['text', 'image'],
        'output' => ['text'],
        'tools' => [
            'stream' => true,
            'file_upload' => env('MODELS_ANTHROPIC_CLAUDE_3_5_HAIKU_TOOLS_FILE_UPLOAD', true),
            'vision' => env('MODELS_ANTHROPIC_CLAUDE_3_5_HAIKU_TOOLS_VISION', true),
            'web_search' => env('MODELS_ANTHROPIC_CLAUDE_3_5_HAIKU_TOOLS_WEB_SEARCH', true),
        ],
        'external' => env('MODELS_ANTHROPIC_CLAUDE_3_5_HAIKU_EXTERNAL', true),
    ],
    [
        'active' => env('MODELS_ANTHROPIC_CLAUDE_3_OPUS_ACTIVE', true),
        'id' => 'claude-3-opus-20240229',
        'label' => 'Claude 3 Opus',
        'input' => ['text', 'image'],
        'output' => ['text'],
        'tools' => [
            'stream' => true,
            'file_upload' => env('MODELS_ANTHROPIC_CLAUDE_3_OPUS_TOOLS_FILE_UPLOAD', true),
            'vision' => env('MODELS_ANTHROPIC_CLAUDE_3_OPUS_TOOLS_VISION', true),
        ],
        'external' => env('MODELS_ANTHROPIC_CLAUDE_3_OPUS_EXTERNAL', false), // Expensive
    ],
    [
        'active' => env('MODELS_ANTHROPIC_CLAUDE_3_SONNET_ACTIVE', true),
        'id' => 'claude-3-sonnet-20240229',
        'label' => 'Claude 3 Sonnet',
        'input' => ['text', 'image'],
        'output' => ['text'],
        'tools' => [
            'stream' => true,
            'file_upload' => env('MODELS_ANTHROPIC_CLAUDE_3_SONNET_TOOLS_FILE_UPLOAD', true),
            'vision' => env('MODELS_ANTHROPIC_CLAUDE_3_SONNET_TOOLS_VISION', true),
        ],
        'external' => env('MODELS_ANTHROPIC_CLAUDE_3_SONNET_EXTERNAL', true),
    ],
    [
        'active' => env('MODELS_ANTHROPIC_CLAUDE_3_HAIKU_ACTIVE', true),
        'id' => 'claude-3-haiku-20240307',
        'label' => 'Claude 3 Haiku',
        'input' => ['text', 'image'],
        'output' => ['text'],
        'tools' => [
            'stream' => true,
            'file_upload' => env('MODELS_ANTHROPIC_CLAUDE_3_HAIKU_TOOLS_FILE_UPLOAD', true),
            'vision' => env('MODELS_ANTHROPIC_CLAUDE_3_HAIKU_TOOLS_VISION', true),
        ],
        'external' => env('MODELS_ANTHROPIC_CLAUDE_3_HAIKU_EXTERNAL', true),
    ],
    [
        'active' => env('MODELS_ANTHROPIC_CLAUDE_SONNET_4_5_ACTIVE', false),
        'id' => 'claude-sonnet-4-5-20250929',
        'label' => 'Claude Sonnet 4.5',
        'input' => ['text', 'image'],
        'output' => ['text'],
        'tools' => [
            'stream' => true,
            'file_upload' => env('MODELS_ANTHROPIC_CLAUDE_SONNET_4_5_TOOLS_FILE_UPLOAD', true),
            'vision' => env('MODELS_ANTHROPIC_CLAUDE_SONNET_4_5_TOOLS_VISION', true),
            'web_search' => env('MODELS_ANTHROPIC_CLAUDE_SONNET_4_5_TOOLS_WEB_SEARCH', true),
        ],
        'external' => env('MODELS_ANTHROPIC_CLAUDE_SONNET_4_5_EXTERNAL', false),
    ],
    [
        'active' => env('MODELS_ANTHROPIC_CLAUDE_SONNET_4_ACTIVE', false),
        'id' => 'claude-sonnet-4-20250514',
        'label' => 'Claude Sonnet 4',
        'input' => ['text', 'image'],
        'output' => ['text'],
        'tools' => [
            'stream' => true,
            'file_upload' => env('MODELS_ANTHROPIC_CLAUDE_SONNET_4_TOOLS_FILE_UPLOAD', true),
            'vision' => env('MODELS_ANTHROPIC_CLAUDE_SONNET_4_TOOLS_VISION', true),
            'web_search' => env('MODELS_ANTHROPIC_CLAUDE_SONNET_4_TOOLS_WEB_SEARCH', true),
        ],
        'external' => env('MODELS_ANTHROPIC_CLAUDE_SONNET_4_EXTERNAL', false),
    ],
    [
        'active' => env('MODELS_ANTHROPIC_CLAUDE_OPUS_4_1_ACTIVE', false),
        'id' => 'claude-opus-4-1-20250805',
        'label' => 'Claude Opus 4.1',
        'input' => ['text', 'image'],
        'output' => ['text'],
        'tools' => [
            'stream' => true,
            'file_upload' => env('MODELS_ANTHROPIC_CLAUDE_OPUS_4_1_TOOLS_FILE_UPLOAD', true),
            'vision' => env('MODELS_ANTHROPIC_CLAUDE_OPUS_4_1_TOOLS_VISION', true),
            'web_search' => env('MODELS_ANTHROPIC_CLAUDE_OPUS_4_1_TOOLS_WEB_SEARCH', true),
        ],
        'external' => env('MODELS_ANTHROPIC_CLAUDE_OPUS_4_1_EXTERNAL', false),
    ],
    [
        'active' => env('MODELS_ANTHROPIC_CLAUDE_OPUS_4_ACTIVE', false),
        'id' => 'claude-opus-4-20250514',
        'label' => 'Claude Opus 4',
        'input' => ['text', 'image'],
        'output' => ['text'],
        'tools' => [
            'stream' => true,
            'file_upload' => env('MODELS_ANTHROPIC_CLAUDE_OPUS_4_TOOLS_FILE_UPLOAD', true),
            'vision' => env('MODELS_ANTHROPIC_CLAUDE_OPUS_4_TOOLS_VISION', true),
            'web_search' => env('MODELS_ANTHROPIC_CLAUDE_OPUS_4_TOOLS_WEB_SEARCH', true),
        ],
        'external' => env('MODELS_ANTHROPIC_CLAUDE_OPUS_4_EXTERNAL', false),
    ],
    [
        'active' => env('MODELS_ANTHROPIC_CLAUDE_3_7_SONNET_ACTIVE', false),
        'id' => 'claude-3-7-sonnet-20250219',
        'label' => 'Claude 3.7 Sonnet',
        'input' => ['text', 'image'],
        'output' => ['text'],
        'tools' => [
            'stream' => true,
            'file_upload' => env('MODELS_ANTHROPIC_CLAUDE_3_7_SONNET_TOOLS_FILE_UPLOAD', true),
            'vision' => env('MODELS_ANTHROPIC_CLAUDE_3_7_SONNET_TOOLS_VISION', true),
            'web_search' => env('MODELS_ANTHROPIC_CLAUDE_3_7_SONNET_TOOLS_WEB_SEARCH', true),
        ],
        'external' => env('MODELS_ANTHROPIC_CLAUDE_3_7_SONNET_EXTERNAL', false),
    ],
];
