<?php
declare(strict_types=1);


namespace App\Services\Ai\ModelInformation\Enrichment\Implementations\LiteLlm;


use App\Services\Ai\Providers\Values\AiProviderProxy;
use App\Services\System\Container\SystemPaths;
use Illuminate\Support\Str;
use Psr\Log\LoggerInterface;
use Symfony\Component\Filesystem\Path;

/**
 * Reads LiteLLM model data from pre-generated PHP files, one file per provider.
 *
 * These files are generated by {@see StaticLiteLlmDataUpdater} (via the artisan command
 * {@see \App\Console\Commands\Dev\UpdateLiteLlmStaticDataCommand}) and are committed to
 * the repository. They ensure that model information is always available even without a
 * live internet connection or API access.
 *
 * @see LiteLlmApiDataStore for the live-API counterpart with automatic caching.
 */
class StaticLiteLlmDataStore extends AbstractLiteLlmDataStore
{
    public function __construct(
        LoggerInterface                      $logger,
        LiteLlmDriverNameProviderNameMapping $nameMapping,
        private readonly SystemPaths                  $paths,
    )
    {
        parent::__construct($logger, $nameMapping);
    }

    /** Returns the filesystem path to the directory holding all static provider files. */
    public function getStorageDirectoryPath(): string
    {
        return $this->paths->resourcePath('static_llm_data/lite_llm');
    }

    /** Returns the expected file path for a given provider's static data file. */
    public function getProviderFilePath(string $providerName): string
    {
        $providerFileName = 'provider-' . Str::slug($providerName) . '.php';
        return Path::join($this->getStorageDirectoryPath(), $providerFileName);
    }

    /**
     * Requires the static PHP file for the provider and parses its contents.
     *
     * Returns an empty array when the file does not exist or contains invalid data;
     * errors are logged but not re-thrown so the caller can proceed gracefully.
     */
    protected function getProviderModelInformationList(AiProviderProxy $provider): array
    {
        $providerName = $this->nameMapping->getProviderNameFromProxy($provider);
        $providerLogData = [
            'provider_id' => $provider->provider_id,
            'provider_name' => $providerName,
            'provider_adapter_key' => $provider->adapter_key
        ];

        try {
            $providerFilePath = $this->getProviderFilePath($providerName);
            if (!is_readable($providerFilePath)) {
                $this->logger->warning('Static Lite LLM data file not found for provider', [
                    ...$providerLogData,
                    'expected_file' => $providerFilePath,
                ]);
                return [];
            }
            $staticData = require $providerFilePath;
        } catch (\Throwable $e) {
            $this->logger->error('Error fetching provider model information list', [
                ...$providerLogData,
                'exception' => $e,
            ]);
            return [];
        }

        if (!is_array($staticData)) {
            $this->logger->error('Static Lite LLM data is not an array', [
                ...$providerLogData,
                'actual_type' => get_debug_type($staticData),
            ]);
            return [];
        }

        return $this->loadModelDataList($provider, $staticData);
    }
}
