<?php
declare(strict_types=1);
/**
 * This file is auto-generated by StaticLiteLlmDataUpdater.
 * Do not edit this file manually.
 */

return [
    array (
  'id' => 'darkbloom/gemma-4-26b',
  'object' => 'model_catalog.entry',
  'provider' => 'darkbloom',
  'mode' => 'chat',
  'max_input_tokens' => 131072,
  'max_output_tokens' => 32768,
  'max_tokens' => 32768,
  'input_cost_per_token' => 3.0E-8,
  'output_cost_per_token' => 1.65E-7,
  'cache_read_input_token_cost' => NULL,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => true,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => NULL,
  'supports_reasoning' => NULL,
  'supports_response_schema' => NULL,
  'supports_system_messages' => true,
  'supports_web_search' => NULL,
  'source' => 'https://www.darkbloom.dev/',
  'supported_endpoints' => 
  array (
    0 => '/v1/chat/completions',
  ),
  'supports_native_streaming' => true,
  'supports_tool_choice' => true,
),
    array (
  'id' => 'darkbloom/gpt-oss-20b',
  'object' => 'model_catalog.entry',
  'provider' => 'darkbloom',
  'mode' => 'chat',
  'max_input_tokens' => 131072,
  'max_output_tokens' => 32768,
  'max_tokens' => 32768,
  'input_cost_per_token' => 1.45E-8,
  'output_cost_per_token' => 7.0E-8,
  'cache_read_input_token_cost' => NULL,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => true,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => NULL,
  'supports_reasoning' => NULL,
  'supports_response_schema' => NULL,
  'supports_system_messages' => true,
  'supports_web_search' => NULL,
  'source' => 'https://www.darkbloom.dev/',
  'supported_endpoints' => 
  array (
    0 => '/v1/chat/completions',
  ),
  'supports_native_streaming' => true,
  'supports_tool_choice' => true,
),
];
