<?php
declare(strict_types=1);
/**
 * This file is auto-generated by StaticLiteLlmDataUpdater.
 * Do not edit this file manually.
 */

return [
    array (
  'id' => 'tencent/deepseek-v4-pro',
  'object' => 'model_catalog.entry',
  'provider' => 'tencent',
  'mode' => 'chat',
  'max_input_tokens' => 1000000,
  'max_output_tokens' => 384000,
  'max_tokens' => 384000,
  'input_cost_per_token' => 4.35E-7,
  'output_cost_per_token' => 8.7E-7,
  'cache_read_input_token_cost' => 3.625E-9,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => true,
  'supports_parallel_function_calling' => true,
  'supports_vision' => false,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => true,
  'supports_reasoning' => true,
  'supports_response_schema' => true,
  'supports_system_messages' => true,
  'supports_web_search' => NULL,
  'cache_creation_input_token_cost' => 0.0,
  'input_cost_per_token_cache_hit' => 3.625E-9,
  'source' => 'https://www.tencentcloud.com/products/tokenhub',
  'supported_endpoints' => 
  array (
    0 => '/v1/chat/completions',
  ),
  'supports_assistant_prefill' => true,
  'supports_native_streaming' => true,
  'supports_tool_choice' => true,
),
    array (
  'id' => 'tencent/deepseek-v4-flash',
  'object' => 'model_catalog.entry',
  'provider' => 'tencent',
  'mode' => 'chat',
  'max_input_tokens' => 1000000,
  'max_output_tokens' => 384000,
  'max_tokens' => 384000,
  'input_cost_per_token' => 1.4E-7,
  'output_cost_per_token' => 2.8E-7,
  'cache_read_input_token_cost' => 2.8E-9,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => true,
  'supports_parallel_function_calling' => true,
  'supports_vision' => false,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => true,
  'supports_reasoning' => true,
  'supports_response_schema' => true,
  'supports_system_messages' => true,
  'supports_web_search' => NULL,
  'cache_creation_input_token_cost' => 0.0,
  'input_cost_per_token_cache_hit' => 2.8E-9,
  'source' => 'https://www.tencentcloud.com/products/tokenhub',
  'supported_endpoints' => 
  array (
    0 => '/v1/chat/completions',
  ),
  'supports_assistant_prefill' => true,
  'supports_native_streaming' => true,
  'supports_tool_choice' => true,
),
];
