<?php
declare(strict_types=1);
/**
 * This file is auto-generated by StaticLiteLlmDataUpdater.
 * Do not edit this file manually.
 */

return [
    array (
  'id' => 'inception/mercury-2',
  'object' => 'model_catalog.entry',
  'provider' => 'inception',
  'mode' => 'chat',
  'max_input_tokens' => 128000,
  'max_output_tokens' => 50000,
  'max_tokens' => 50000,
  'input_cost_per_token' => 2.5E-7,
  'output_cost_per_token' => 7.5E-7,
  'cache_read_input_token_cost' => 2.5E-8,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => true,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => true,
  'supports_reasoning' => NULL,
  'supports_response_schema' => true,
  'supports_system_messages' => true,
  'supports_web_search' => NULL,
  'supports_tool_choice' => true,
),
];
