<?php
declare(strict_types=1);
/**
 * This file is auto-generated by StaticLiteLlmDataUpdater.
 * Do not edit this file manually.
 */

return [
    array (
  'id' => 'chatdolphin',
  'object' => 'model_catalog.entry',
  'provider' => 'nlp_cloud',
  'mode' => 'chat',
  'max_input_tokens' => 16384,
  'max_output_tokens' => 16384,
  'max_tokens' => 16384,
  'input_cost_per_token' => 5.0E-7,
  'output_cost_per_token' => 5.0E-7,
  'cache_read_input_token_cost' => NULL,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => NULL,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => NULL,
  'supports_reasoning' => NULL,
  'supports_response_schema' => NULL,
  'supports_system_messages' => NULL,
  'supports_web_search' => NULL,
),
    array (
  'id' => 'dolphin',
  'object' => 'model_catalog.entry',
  'provider' => 'nlp_cloud',
  'mode' => 'completion',
  'max_input_tokens' => 16384,
  'max_output_tokens' => 16384,
  'max_tokens' => 16384,
  'input_cost_per_token' => 5.0E-7,
  'output_cost_per_token' => 5.0E-7,
  'cache_read_input_token_cost' => NULL,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => NULL,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => NULL,
  'supports_reasoning' => NULL,
  'supports_response_schema' => NULL,
  'supports_system_messages' => NULL,
  'supports_web_search' => NULL,
),
];
