<?php
declare(strict_types=1);
/**
 * This file is auto-generated by StaticLiteLlmDataUpdater.
 * Do not edit this file manually.
 */

return [
    array (
  'id' => 'sarvam/sarvam-m',
  'object' => 'model_catalog.entry',
  'provider' => 'sarvam',
  'mode' => 'chat',
  'max_input_tokens' => 8192,
  'max_output_tokens' => 32000,
  'max_tokens' => 32000,
  'input_cost_per_token' => 0.0,
  'output_cost_per_token' => 0.0,
  'cache_read_input_token_cost' => 0.0,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => NULL,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => NULL,
  'supports_reasoning' => true,
  'supports_response_schema' => NULL,
  'supports_system_messages' => NULL,
  'supports_web_search' => NULL,
  'cache_creation_input_token_cost' => 0,
  'cache_creation_input_token_cost_above_1hr' => 0,
),
];
