<?php
declare(strict_types=1);
/**
 * This file is auto-generated by StaticLiteLlmDataUpdater.
 * Do not edit this file manually.
 */

return [
    array (
  'id' => 'runwayml/gen4_turbo',
  'object' => 'model_catalog.entry',
  'provider' => 'runwayml',
  'mode' => 'video_generation',
  'max_input_tokens' => NULL,
  'max_output_tokens' => NULL,
  'max_tokens' => NULL,
  'input_cost_per_token' => NULL,
  'output_cost_per_token' => NULL,
  'cache_read_input_token_cost' => NULL,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => NULL,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => NULL,
  'supports_reasoning' => NULL,
  'supports_response_schema' => NULL,
  'supports_system_messages' => NULL,
  'supports_web_search' => NULL,
  'output_cost_per_video_per_second' => 0.05,
  'source' => 'https://docs.dev.runwayml.com/guides/pricing/',
  'supported_modalities' => 
  array (
    0 => 'text',
    1 => 'image',
  ),
  'supported_output_modalities' => 
  array (
    0 => 'video',
  ),
  'supported_resolutions' => 
  array (
    0 => '1280x720',
    1 => '720x1280',
  ),
  'metadata' => 
  array (
    'comment' => '5 credits per second @ $0.01 per credit = $0.05 per second',
  ),
),
    array (
  'id' => 'runwayml/gen4_aleph',
  'object' => 'model_catalog.entry',
  'provider' => 'runwayml',
  'mode' => 'video_generation',
  'max_input_tokens' => NULL,
  'max_output_tokens' => NULL,
  'max_tokens' => NULL,
  'input_cost_per_token' => NULL,
  'output_cost_per_token' => NULL,
  'cache_read_input_token_cost' => NULL,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => NULL,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => NULL,
  'supports_reasoning' => NULL,
  'supports_response_schema' => NULL,
  'supports_system_messages' => NULL,
  'supports_web_search' => NULL,
  'output_cost_per_video_per_second' => 0.15,
  'source' => 'https://docs.dev.runwayml.com/guides/pricing/',
  'supported_modalities' => 
  array (
    0 => 'text',
    1 => 'image',
  ),
  'supported_output_modalities' => 
  array (
    0 => 'video',
  ),
  'supported_resolutions' => 
  array (
    0 => '1280x720',
    1 => '720x1280',
  ),
  'metadata' => 
  array (
    'comment' => '15 credits per second @ $0.01 per credit = $0.15 per second',
  ),
),
    array (
  'id' => 'runwayml/gen3a_turbo',
  'object' => 'model_catalog.entry',
  'provider' => 'runwayml',
  'mode' => 'video_generation',
  'max_input_tokens' => NULL,
  'max_output_tokens' => NULL,
  'max_tokens' => NULL,
  'input_cost_per_token' => NULL,
  'output_cost_per_token' => NULL,
  'cache_read_input_token_cost' => NULL,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => NULL,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => NULL,
  'supports_reasoning' => NULL,
  'supports_response_schema' => NULL,
  'supports_system_messages' => NULL,
  'supports_web_search' => NULL,
  'output_cost_per_video_per_second' => 0.05,
  'source' => 'https://docs.dev.runwayml.com/guides/pricing/',
  'supported_modalities' => 
  array (
    0 => 'text',
    1 => 'image',
  ),
  'supported_output_modalities' => 
  array (
    0 => 'video',
  ),
  'supported_resolutions' => 
  array (
    0 => '1280x720',
    1 => '720x1280',
  ),
  'metadata' => 
  array (
    'comment' => '5 credits per second @ $0.01 per credit = $0.05 per second',
  ),
),
    array (
  'id' => 'runwayml/gen4_image',
  'object' => 'model_catalog.entry',
  'provider' => 'runwayml',
  'mode' => 'image_generation',
  'max_input_tokens' => NULL,
  'max_output_tokens' => NULL,
  'max_tokens' => NULL,
  'input_cost_per_token' => NULL,
  'output_cost_per_token' => NULL,
  'cache_read_input_token_cost' => NULL,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => NULL,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => NULL,
  'supports_reasoning' => NULL,
  'supports_response_schema' => NULL,
  'supports_system_messages' => NULL,
  'supports_web_search' => NULL,
  'input_cost_per_image' => 0.05,
  'output_cost_per_image' => 0.05,
  'source' => 'https://docs.dev.runwayml.com/guides/pricing/',
  'supported_modalities' => 
  array (
    0 => 'text',
    1 => 'image',
  ),
  'supported_output_modalities' => 
  array (
    0 => 'image',
  ),
  'supported_resolutions' => 
  array (
    0 => '1280x720',
    1 => '1920x1080',
  ),
  'metadata' => 
  array (
    'comment' => '5 credits per 720p image or 8 credits per 1080p image @ $0.01 per credit. Using 5 credits ($0.05) as base cost',
  ),
),
    array (
  'id' => 'runwayml/gen4_image_turbo',
  'object' => 'model_catalog.entry',
  'provider' => 'runwayml',
  'mode' => 'image_generation',
  'max_input_tokens' => NULL,
  'max_output_tokens' => NULL,
  'max_tokens' => NULL,
  'input_cost_per_token' => NULL,
  'output_cost_per_token' => NULL,
  'cache_read_input_token_cost' => NULL,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => NULL,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => NULL,
  'supports_reasoning' => NULL,
  'supports_response_schema' => NULL,
  'supports_system_messages' => NULL,
  'supports_web_search' => NULL,
  'input_cost_per_image' => 0.02,
  'output_cost_per_image' => 0.02,
  'source' => 'https://docs.dev.runwayml.com/guides/pricing/',
  'supported_modalities' => 
  array (
    0 => 'text',
    1 => 'image',
  ),
  'supported_output_modalities' => 
  array (
    0 => 'image',
  ),
  'supported_resolutions' => 
  array (
    0 => '1280x720',
    1 => '1920x1080',
  ),
  'metadata' => 
  array (
    'comment' => '2 credits per image (any resolution) @ $0.01 per credit = $0.02 per image',
  ),
),
    array (
  'id' => 'runwayml/eleven_multilingual_v2',
  'object' => 'model_catalog.entry',
  'provider' => 'runwayml',
  'mode' => 'audio_speech',
  'max_input_tokens' => NULL,
  'max_output_tokens' => NULL,
  'max_tokens' => NULL,
  'input_cost_per_token' => NULL,
  'output_cost_per_token' => NULL,
  'cache_read_input_token_cost' => NULL,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => NULL,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => NULL,
  'supports_reasoning' => NULL,
  'supports_response_schema' => NULL,
  'supports_system_messages' => NULL,
  'supports_web_search' => NULL,
  'input_cost_per_character' => 3.0E-7,
  'source' => 'https://docs.dev.runwayml.com/guides/pricing/',
  'metadata' => 
  array (
    'comment' => 'Estimated cost based on standard TTS pricing. RunwayML uses ElevenLabs models.',
  ),
),
];
