<?php
declare(strict_types=1);
/**
 * This file is auto-generated by StaticLiteLlmDataUpdater.
 * Do not edit this file manually.
 */

return [
    array (
  'id' => 'firecrawl/search',
  'object' => 'model_catalog.entry',
  'provider' => 'firecrawl',
  'mode' => 'search',
  'max_input_tokens' => NULL,
  'max_output_tokens' => NULL,
  'max_tokens' => NULL,
  'input_cost_per_token' => NULL,
  'output_cost_per_token' => NULL,
  'cache_read_input_token_cost' => NULL,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => NULL,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => NULL,
  'supports_reasoning' => NULL,
  'supports_response_schema' => NULL,
  'supports_system_messages' => NULL,
  'supports_web_search' => NULL,
  'tiered_pricing' => 
  array (
    0 => 
    array (
      'input_cost_per_query' => 0.00166,
      'max_results_range' => 
      array (
        0 => 1,
        1 => 10,
      ),
    ),
    1 => 
    array (
      'input_cost_per_query' => 0.00332,
      'max_results_range' => 
      array (
        0 => 11,
        1 => 20,
      ),
    ),
    2 => 
    array (
      'input_cost_per_query' => 0.00498,
      'max_results_range' => 
      array (
        0 => 21,
        1 => 30,
      ),
    ),
    3 => 
    array (
      'input_cost_per_query' => 0.00664,
      'max_results_range' => 
      array (
        0 => 31,
        1 => 40,
      ),
    ),
    4 => 
    array (
      'input_cost_per_query' => 0.0083,
      'max_results_range' => 
      array (
        0 => 41,
        1 => 50,
      ),
    ),
    5 => 
    array (
      'input_cost_per_query' => 0.00996,
      'max_results_range' => 
      array (
        0 => 51,
        1 => 60,
      ),
    ),
    6 => 
    array (
      'input_cost_per_query' => 0.01162,
      'max_results_range' => 
      array (
        0 => 61,
        1 => 70,
      ),
    ),
    7 => 
    array (
      'input_cost_per_query' => 0.01328,
      'max_results_range' => 
      array (
        0 => 71,
        1 => 80,
      ),
    ),
    8 => 
    array (
      'input_cost_per_query' => 0.01494,
      'max_results_range' => 
      array (
        0 => 81,
        1 => 90,
      ),
    ),
    9 => 
    array (
      'input_cost_per_query' => 0.0166,
      'max_results_range' => 
      array (
        0 => 91,
        1 => 100,
      ),
    ),
  ),
  'metadata' => 
  array (
    'notes' => 'Firecrawl search pricing: $83 for 100,000 credits, 2 credits per 10 results. Cost = ceiling(limit/10) * 2 * $0.00083',
  ),
),
];
