<?php
declare(strict_types=1);
/**
 * This file is auto-generated by StaticLiteLlmDataUpdater.
 * Do not edit this file manually.
 */

return [
    array (
  'id' => 'exa_ai/search',
  'object' => 'model_catalog.entry',
  'provider' => 'exa_ai',
  'mode' => 'search',
  'max_input_tokens' => NULL,
  'max_output_tokens' => NULL,
  'max_tokens' => NULL,
  'input_cost_per_token' => NULL,
  'output_cost_per_token' => NULL,
  'cache_read_input_token_cost' => NULL,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => NULL,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => NULL,
  'supports_reasoning' => NULL,
  'supports_response_schema' => NULL,
  'supports_system_messages' => NULL,
  'supports_web_search' => NULL,
  'tiered_pricing' => 
  array (
    0 => 
    array (
      'input_cost_per_query' => 0.005,
      'max_results_range' => 
      array (
        0 => 0,
        1 => 25,
      ),
    ),
    1 => 
    array (
      'input_cost_per_query' => 0.025,
      'max_results_range' => 
      array (
        0 => 26,
        1 => 100,
      ),
    ),
  ),
),
];
