<?php
declare(strict_types=1);
/**
 * This file is auto-generated by StaticLiteLlmDataUpdater.
 * Do not edit this file manually.
 */

return [
    array (
  'id' => 'vertex_ai/zai-org/glm-4.7-maas',
  'object' => 'model_catalog.entry',
  'provider' => 'vertex_ai-zai_models',
  'mode' => 'chat',
  'max_input_tokens' => 200000,
  'max_output_tokens' => 128000,
  'max_tokens' => 128000,
  'input_cost_per_token' => 6.0E-7,
  'output_cost_per_token' => 2.2E-6,
  'cache_read_input_token_cost' => NULL,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => true,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => NULL,
  'supports_reasoning' => true,
  'supports_response_schema' => NULL,
  'supports_system_messages' => NULL,
  'supports_web_search' => NULL,
  'source' => 'https://cloud.google.com/vertex-ai/generative-ai/pricing#partner-models',
  'supported_regions' => 
  array (
    0 => 'global',
  ),
  'supports_tool_choice' => true,
),
    array (
  'id' => 'vertex_ai/zai-org/glm-5-maas',
  'object' => 'model_catalog.entry',
  'provider' => 'vertex_ai-zai_models',
  'mode' => 'chat',
  'max_input_tokens' => 200000,
  'max_output_tokens' => 128000,
  'max_tokens' => 128000,
  'input_cost_per_token' => 1.0E-6,
  'output_cost_per_token' => 3.2E-6,
  'cache_read_input_token_cost' => 1.0E-7,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => true,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => true,
  'supports_reasoning' => true,
  'supports_response_schema' => NULL,
  'supports_system_messages' => NULL,
  'supports_web_search' => NULL,
  'source' => 'https://cloud.google.com/vertex-ai/generative-ai/pricing#glm-models',
  'supported_regions' => 
  array (
    0 => 'global',
  ),
  'supports_tool_choice' => true,
),
];
