<?php
declare(strict_types=1);
/**
 * This file is auto-generated by StaticLiteLlmDataUpdater.
 * Do not edit this file manually.
 */

return [
    array (
  'id' => 'soniox/stt-async-v4',
  'object' => 'model_catalog.entry',
  'provider' => 'soniox',
  'mode' => 'audio_transcription',
  'max_input_tokens' => NULL,
  'max_output_tokens' => 8000,
  'max_tokens' => 8000,
  'input_cost_per_token' => NULL,
  'output_cost_per_token' => NULL,
  'cache_read_input_token_cost' => NULL,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => NULL,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => true,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => NULL,
  'supports_reasoning' => NULL,
  'supports_response_schema' => NULL,
  'supports_system_messages' => NULL,
  'supports_web_search' => NULL,
  'input_cost_per_second' => 0.0,
  'output_cost_per_second' => 2.77778E-5,
  'source' => 'https://soniox.com/pricing',
  'supported_endpoints' => 
  array (
    0 => '/v1/audio/transcriptions',
  ),
),
    array (
  'id' => 'soniox/stt-async-v5',
  'object' => 'model_catalog.entry',
  'provider' => 'soniox',
  'mode' => 'audio_transcription',
  'max_input_tokens' => NULL,
  'max_output_tokens' => 8000,
  'max_tokens' => 8000,
  'input_cost_per_token' => NULL,
  'output_cost_per_token' => NULL,
  'cache_read_input_token_cost' => NULL,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => NULL,
  'supports_parallel_function_calling' => NULL,
  'supports_vision' => NULL,
  'supports_audio_input' => true,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => NULL,
  'supports_reasoning' => NULL,
  'supports_response_schema' => NULL,
  'supports_system_messages' => NULL,
  'supports_web_search' => NULL,
  'input_cost_per_second' => 0.0,
  'output_cost_per_second' => 2.77778E-5,
  'source' => 'https://soniox.com/pricing',
  'supported_endpoints' => 
  array (
    0 => '/v1/audio/transcriptions',
  ),
),
];
