<?php
declare(strict_types=1);
/**
 * This file is auto-generated by StaticLiteLlmDataUpdater.
 * Do not edit this file manually.
 */

return [
    array (
  'id' => 'meta/muse-spark-1.1',
  'object' => 'model_catalog.entry',
  'provider' => 'meta',
  'mode' => 'chat',
  'max_input_tokens' => 1048576,
  'max_output_tokens' => 131072,
  'max_tokens' => 131072,
  'input_cost_per_token' => 1.25E-6,
  'output_cost_per_token' => 4.25E-6,
  'cache_read_input_token_cost' => 1.5E-7,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => true,
  'supports_parallel_function_calling' => true,
  'supports_vision' => true,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => true,
  'supports_reasoning' => true,
  'supports_response_schema' => true,
  'supports_system_messages' => true,
  'supports_web_search' => true,
  'search_context_cost_per_query' => 
  array (
    'search_context_size_high' => 0.0025,
    'search_context_size_low' => 0.0025,
    'search_context_size_medium' => 0.0025,
  ),
  'source' => 'https://dev.meta.ai/docs/getting-started/pricing-rate-limits',
  'supported_endpoints' => 
  array (
    0 => '/v1/chat/completions',
    1 => '/v1/responses',
    2 => '/v1/messages',
  ),
  'supported_modalities' => 
  array (
    0 => 'text',
    1 => 'image',
    2 => 'video',
  ),
  'supported_output_modalities' => 
  array (
    0 => 'text',
  ),
  'supports_minimal_reasoning_effort' => true,
  'supports_pdf_input' => true,
  'supports_tool_choice' => true,
  'supports_xhigh_reasoning_effort' => true,
),
    array (
  'id' => 'meta/muse-spark-1.2',
  'object' => 'model_catalog.entry',
  'provider' => 'meta',
  'mode' => 'chat',
  'max_input_tokens' => 1048576,
  'max_output_tokens' => 131072,
  'max_tokens' => 131072,
  'input_cost_per_token' => 1.25E-6,
  'output_cost_per_token' => 4.25E-6,
  'cache_read_input_token_cost' => 1.5E-7,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => true,
  'supports_parallel_function_calling' => true,
  'supports_vision' => true,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => true,
  'supports_reasoning' => true,
  'supports_response_schema' => true,
  'supports_system_messages' => true,
  'supports_web_search' => true,
  'search_context_cost_per_query' => 
  array (
    'search_context_size_high' => 0.0025,
    'search_context_size_low' => 0.0025,
    'search_context_size_medium' => 0.0025,
  ),
  'source' => 'https://dev.meta.ai/docs/getting-started/pricing-rate-limits',
  'supported_endpoints' => 
  array (
    0 => '/v1/chat/completions',
    1 => '/v1/responses',
    2 => '/v1/messages',
  ),
  'supported_modalities' => 
  array (
    0 => 'text',
    1 => 'image',
    2 => 'video',
  ),
  'supported_output_modalities' => 
  array (
    0 => 'text',
  ),
  'supports_minimal_reasoning_effort' => true,
  'supports_pdf_input' => true,
  'supports_tool_choice' => true,
  'supports_xhigh_reasoning_effort' => true,
),
    array (
  'id' => 'meta/muse-spark-1.2-contributor',
  'object' => 'model_catalog.entry',
  'provider' => 'meta',
  'mode' => 'chat',
  'max_input_tokens' => 1048576,
  'max_output_tokens' => 131072,
  'max_tokens' => 131072,
  'input_cost_per_token' => 1.0E-7,
  'output_cost_per_token' => 2.0E-7,
  'cache_read_input_token_cost' => 2.0E-9,
  'input_cost_per_audio_token' => NULL,
  'output_cost_per_reasoning_token' => NULL,
  'deprecation_date' => NULL,
  'supports_function_calling' => true,
  'supports_parallel_function_calling' => true,
  'supports_vision' => true,
  'supports_audio_input' => NULL,
  'supports_audio_output' => NULL,
  'supports_prompt_caching' => true,
  'supports_reasoning' => true,
  'supports_response_schema' => true,
  'supports_system_messages' => true,
  'supports_web_search' => true,
  'search_context_cost_per_query' => 
  array (
    'search_context_size_high' => 0.0025,
    'search_context_size_low' => 0.0025,
    'search_context_size_medium' => 0.0025,
  ),
  'source' => 'https://dev.meta.ai/docs/getting-started/pricing-rate-limits',
  'supported_endpoints' => 
  array (
    0 => '/v1/chat/completions',
    1 => '/v1/responses',
    2 => '/v1/messages',
  ),
  'supported_modalities' => 
  array (
    0 => 'text',
    1 => 'image',
    2 => 'video',
  ),
  'supported_output_modalities' => 
  array (
    0 => 'text',
  ),
  'supports_minimal_reasoning_effort' => true,
  'supports_pdf_input' => true,
  'supports_tool_choice' => true,
  'supports_xhigh_reasoning_effort' => true,
),
];
