// Auto-generated by vitePluginBreakpoints — do not edit manually.
import type { Snippet } from 'svelte';

export const breakpointsQueries = {
    bpXxs: '(max-width: 300px)',
    bpBiggerThanXxs: '(min-width: 300px)',
    bpXs: '(max-width: 549px)',
    bpXsAndSmaller: '(max-width: 549px)',
    bpBiggerThanXs: '(min-width: 549px)',
    bpSmallerThanSm: '(max-width: 550px)',
    bpSm: '(min-width: 550px) and (max-width: 767px)',
    bpSmAndSmaller: '(max-width: 767px)',
    bpSmAndBigger: '(min-width: 550px)',
    bpBiggerThanSm: '(min-width: 767px)',
    bpSmallerThanMd: '(max-width: 768px)',
    bpMd: '(min-width: 768px) and (max-width: 991px)',
    bpMdAndSmaller: '(max-width: 991px)',
    bpMdAndBigger: '(min-width: 768px)',
    bpBiggerThanMd: '(min-width: 991px)',
    bpSmallerThanLg: '(max-width: 992px)',
    bpLg: '(min-width: 992px) and (max-width: 1199px)',
    bpLgAndSmaller: '(max-width: 1199px)',
    bpLgAndBigger: '(min-width: 992px)',
    bpBiggerThanLg: '(min-width: 1199px)',
    bpSmallerThanXl: '(max-width: 1200px)',
    bpXl: '(min-width: 1200px)',
} as const;

export type Breakpoint = keyof typeof breakpointsQueries;

export interface BreakpointExactProps {
    bpXxs?: Snippet;
    bpXs?: Snippet;
    bpSm?: Snippet;
    bpMd?: Snippet;
    bpLg?: Snippet;
    bpXl?: Snippet;
}

export interface BreakpointRangeProps {
    bpBiggerThanXxs?: Snippet;
    bpXsAndSmaller?: Snippet;
    bpBiggerThanXs?: Snippet;
    bpSmallerThanSm?: Snippet;
    bpSmAndSmaller?: Snippet;
    bpSmAndBigger?: Snippet;
    bpBiggerThanSm?: Snippet;
    bpSmallerThanMd?: Snippet;
    bpMdAndSmaller?: Snippet;
    bpMdAndBigger?: Snippet;
    bpBiggerThanMd?: Snippet;
    bpSmallerThanLg?: Snippet;
    bpLgAndSmaller?: Snippet;
    bpLgAndBigger?: Snippet;
    bpBiggerThanLg?: Snippet;
    bpSmallerThanXl?: Snippet;
}

export interface BreakpointSnippetProps extends BreakpointExactProps, BreakpointRangeProps {
    /** Rendered only when no breakpoint snippet matches the current viewport. */
    children?: Snippet;
}
