// Auto-generated by vitePluginBreakpoints — do not edit manually.
import type { Snippet } from 'svelte';

/**
 * Map of breakpoint name → `matchMedia` query string, generated from the
 * `--bp-*` CSS custom-media definitions (see the Svelte-standard breakpoint
 * table: `xxs`/`xs`/`sm`/`md`/`lg`/`xl`, plus `*AndSmaller`/`*AndBigger`/
 * `smallerThan*`/`biggerThan*` range variants).
 *
 * This is the single source of truth consumed by {@link useBreakpoint} (JS
 * side, via `matchMedia`) and by `Breakpoint.svelte` (which named snippet
 * matches). You should not need to read this object directly — use
 * `useBreakpoint()` or `<Breakpoint>` instead.
 */
export const breakpointsQueries = {
    bpXxs: '(max-width: 300px)',
    bpBiggerThanXxs: '(min-width: 300px)',
    bpXs: '(max-width: 549px)',
    bpXsAndSmaller: '(max-width: 549px)',
    bpBiggerThanXs: '(min-width: 549px)',
    bpSmallerThanSm: '(max-width: 550px)',
    bpSm: '(min-width: 550px) and (max-width: 767px)',
    bpSmAndSmaller: '(max-width: 767px)',
    bpSmAndBigger: '(min-width: 550px)',
    bpBiggerThanSm: '(min-width: 767px)',
    bpSmallerThanMd: '(max-width: 768px)',
    bpMd: '(min-width: 768px) and (max-width: 991px)',
    bpMdAndSmaller: '(max-width: 991px)',
    bpMdAndBigger: '(min-width: 768px)',
    bpBiggerThanMd: '(min-width: 991px)',
    bpSmallerThanLg: '(max-width: 992px)',
    bpLg: '(min-width: 992px) and (max-width: 1199px)',
    bpLgAndSmaller: '(max-width: 1199px)',
    bpLgAndBigger: '(min-width: 992px)',
    bpBiggerThanLg: '(min-width: 1199px)',
    bpSmallerThanXl: '(max-width: 1200px)',
    bpXl: '(min-width: 1200px)',
} as const;

/** Union of every valid breakpoint name (the keys of {@link breakpointsQueries}). */
export type Breakpoint = keyof typeof breakpointsQueries;

/** Named snippet props for the exact (non-overlapping) breakpoint ranges,
 *  e.g. `bpSm` matches only 550–767px, not "550px and up". Spread into
 *  `Breakpoint.svelte`'s `Props` via {@link BreakpointSnippetProps}. */
export interface BreakpointExactProps {
    bpXxs?: Snippet;
    bpXs?: Snippet;
    bpSm?: Snippet;
    bpMd?: Snippet;
    bpLg?: Snippet;
    bpXl?: Snippet;
}

/** Named snippet props for the open-ended/overlapping breakpoint ranges
 *  (`*AndSmaller`, `*AndBigger`, `smallerThan*`, `biggerThan*`). Spread into
 *  `Breakpoint.svelte`'s `Props` via {@link BreakpointSnippetProps}. */
export interface BreakpointRangeProps {
    bpBiggerThanXxs?: Snippet;
    bpXsAndSmaller?: Snippet;
    bpBiggerThanXs?: Snippet;
    bpSmallerThanSm?: Snippet;
    bpSmAndSmaller?: Snippet;
    bpSmAndBigger?: Snippet;
    bpBiggerThanSm?: Snippet;
    bpSmallerThanMd?: Snippet;
    bpMdAndSmaller?: Snippet;
    bpMdAndBigger?: Snippet;
    bpBiggerThanMd?: Snippet;
    bpSmallerThanLg?: Snippet;
    bpLgAndSmaller?: Snippet;
    bpLgAndBigger?: Snippet;
    bpBiggerThanLg?: Snippet;
    bpSmallerThanXl?: Snippet;
}

export interface BreakpointSnippetProps extends BreakpointExactProps, BreakpointRangeProps {
    /** Rendered only when no breakpoint snippet matches the current viewport. */
    children?: Snippet;
}
