name: '[MANUAL] - 1. Create Release Branch'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (semver, e.g. 2.1.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release-branch:
    name: Create release/v${{ inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - uses: hawk-digital-environments/hawk-pipeline-actions/create-release-branch@v1
        with:
          version: ${{ inputs.version }}
          version-json: config/hawki_version.json
          # This ensures that the model provider config files are updated in the release branch
          # so our docker setup will match the current state of the main config files.
          shell: |
            rm -f _docker_production/config/model_providers.php
            cp config/model_providers.php _docker_production/config/model_providers.php
            rm -rf _docker_production/config/model_lists
            cp -r config/model_lists _docker_production/config/model_lists
            git add _docker_production/config/model_lists
