name: Release

on:
  release:
    types: [published]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/dwggroup/HAWKI:${{ github.ref_name }}
          cache-from: "type=registry,ref=ghcr.io/dwggroup/HAWKI:buildcache"
          cache-to: "type=registry,ref=ghcr.io/dwggroup/HAWKI:buildcache,mode=max"